### PR TITLE
Function request Dynamic routes

### PR DESCRIPTION
**Pull request by iligalodin**
Added feature:
added efficient routes for all three days starting from the northeast to the southwest of the map.
the route changes if you disable/enable a node, if you have a node already marked collected via cookies it will ignore it and add it back if you reset the node/ all nodes

todo:
Will add the json via a direct commit
currently routing day three

### CODE REVIEW

**Comment by jeanropke** [comment]
Need rewrite some parts of the code.
Enable routes then change the day.

**Comment by iligalodin** [comment]
the routes are day dependent though

**Comment by iligalodin** [comment]
inless i dont understand what you were saying

**Comment by Rakmarok** [comment]
Great work on this! I did some testing and found the following issues:

- The symbols for Necklaces and Earrings are flipped in the list and the map.

### Day 1 has the following items missing from the route creation (tested all item categories on their own):

**American Wild Flowers**: 
image

**Bird Eggs**:
image
(The unmarked egg is the Eagle egg.)

**Family Heirlooms**:
image
(The unmarked heirloom is the Boar Bristle Brush.)

**Lost Jewelry: Earrings**:
image

- All of these items are also ignored when having everything shown and the route enabled. 

### Day 2 has the following items missing from the route creation (tested all item categories on their own):

**American Wild Flowers**:
image
(The unmarked flower is an Agarita.)

**Antique Alcohol Bottles**:
image
(The unmarked bottle is the Cognac Bottle.)

**Bird Eggs**:
image

**Coins**:
image
(The unmarked coin is the 1800 Gold Dollar Coin.)

**Family Heirlooms**:
image

**Lost Jewelry: Bracelets**:
image

**Lost Jewelry: Necklaces**:
image
(The unmarked necklace is the Tuamotu Pearl Necklace.) 

**Tarot Cards: Cups**:
image

- All of these items are also ignored when having everything shown and the route enabled. 

### Day 3 isn't working at all (I assume because you're still working on it, so all good).

**Comment by Rakmarok** [comment]
> Need rewrite some parts of the code.
> Enable routes then change the day.

I think he meant that routes don't change when switching days manually until turned off and on again? @iligalodin

**Comment by iligalodin** [comment]
it's strange that you are missing some items on the route. I excluded some duplicate items like flowers and eggs however the other items its strange... .ill check immediately

**Comment by iligalodin** [comment]
it should be fixed now, i am indeed working on day three

**Comment by Rakmarok** [comment]
> it should be fixed now, i am indeed working on day three

After my first test, it indeed seems to be fixed. I was confused for a second why some eggs and flowers were still missing but then I remembered that you mentioned you removed duplicates - everything should be good now. 

Today is day 3, so hurry up! ;-)

(Just joking of course. I would help if I knew how to code.)

**Comment by AnuKaro** [comment]
This is just awesome! Great work

**Pull request merged**
