### PR TITLE
Items value counter

### PR DESCRIPTION
**Pull request by MichalD96**
Items counter will display in menu current value of all collected items and full sets

### CODE REVIEW

**Comment by Senexis** [comment]
Doesn't seem to work properly. Stuck at $0.00.

**Comment by MichalD96** [comment]
i have the latest version, and here works:
https://michald96.github.io/RDR2CollectorsMap/

it works only if you add item to the inventory (not if you disable it from menu)

**Comment by MichalD96** [comment]
ok, i know what you mean, it is stuck on 0.00$ onload, when inventory is disabled

**Comment by Senexis** [comment]
I noticed that you only hide the totals when you check the checkbox, but not on page load. :)

**Comment by MichalD96** [comment]
yes, i didn't notice that earlier

**Comment by Senexis** [comment]
Honestly, might be better if you could make it work for both inventory enabled and disabled, but it's fine if it's working for now. Just fix those bugs and I'll merge it. 🙂

**Comment by Senexis** [comment]
Something's also weird when you collect a few then reload. When I remove those items from my inventory the total stays stuck now. So pretty much, collect some, reload, remove some, total stays the same.

**Comment by MichalD96** [comment]
what is the sense to make it work with disabled inventory? it should count only items in this inventory.
about your last comment, it works fine for me. when i reload the map, everything is loaded properly and it's not stuck

**Comment by MichalD96** [comment]
it is not work like that, everything is ok
it it not related to disabled items in menu, it base ONLY on your inventory items

**Comment by MichalD96** [comment]
this is fine, because 0 of 211 count items  disabled in existing cycle, and it counts only items disabled in menu. but my items value base on all items  added to the inventory

**Comment by Senexis** [comment]
> 
> 
> this is fine, because 0 of 211 count items disabled in existing cycle, and it counts only items disabled in menu. but my items value base on all items added to the inventory
> You can have 0 items disabled in this cycle, but still some items in the inventory collected earlier

Sure, but I removed them on the same page. So I'd expect them to get removed if I remove them myself explicitly. :P

**Comment by MichalD96** [comment]
if you "un-collect" the item it gets removed from the inventory, so the value should be decreased.
I dont know excactly what you mean
it doesnt work only if you have unchecked "Toggling menu items updates inventory" so in this case you have to use + and -

**Comment by MichalD96** [comment]
if you mean thae case when you disable item, then enable inventory, and this item is not counted -
it is inventory problem, because item have not been added to the inventory after re-enabling it

**Comment by MichalD96** [comment]
lets see if ppl will need this when inventory is disabled
it require to add function that checks disabled items, but would be cool to fix this bug with disabled items first

**Comment by Senexis** [comment]
> if you "un-collect" the item **it gets removed from the inventory, so the value should be decreased**.
> I dont know excactly what you mean
> it doesnt work only if you have unchecked "Toggling menu items updates inventory" so in this case you have to use + and -

That's the thing, if you refresh and then remove it, it doesn't get decreased.

**Comment by MichalD96** [comment]
Yes, i know about it, but this is inventory bug. Inventory system need some fixes.
I can look at it layer when i come back home

**Pull request merged**
