### PR TITLE
added Nazar support

### PR DESCRIPTION
**Pull request by iligalodin**
added the location of nazar, will upload icon soon.

don't know how the hide show function is added if someone else can that would be great!

### CODE REVIEW

**Comment by jeanropke** [comment]
I'll check with NazarFinder API dev if all the access will overload Heroku dynos before merging.

**Comment by iligalodin** [comment]
should not overload, i've done it so the json only loads on init

**Comment by jeanropke** [comment]
Heroku free dynos are very limited.
Analytics right now http://prntscr.com/pd0838

**Comment by jeanropke** [comment]
I changed your code, disabled the request to MadamNazar API.

**Comment by iligalodin** [comment]
how will it work now?

**Comment by jeanropke** [comment]
Update manualy to next position by now.

**Comment by iligalodin** [comment]
just for science lets note it down
Monday locations 1
Tuesday locations:
wednessday locations: 
thursday locations: 
friday locations: 
saturday locations: 
sunday locations:

**Pull request closed without merging**
