### PR TITLE
Support any color selection in marker color customization

### PR DESCRIPTION
**Pull request by gebederry**
Hello,
This PR primarily optimizes the color picker by supporting any color selection, and adds a new marker background image, a pushpin shape, to the pin edit options. These changes were implemented using [pickr](https://github.com/Simonwep/pickr), as the previously used Coloris was too lightweight and had some styling bugs. Additionally, this PR adds several map-related zoom and wheel settings to the side menu, and integrates a lightweight well-established library [plain-draggable](https://github.com/anseki/plain-draggable) to enable drag functionality for the Lat/Lng indicator.

### CODE REVIEW

**Comment by gebederry** [comment]
https://github.com/jeanropke/RDR2CollectorsMap/pull/1275/commits/10e8764ff87886ad62f9bdd518a87b8d0e39f86a
- added a new font [RDRCatalogueBold](https://s.rsg.sc/sc/fonts/rdr2catalogue/catalog-bold/RDRCatalogueBold-Bold.woff2) to be used as the button text font.
- collapsed some paragraphs in the legendary animal popup to reduce the overall height. This ensures that when the popup height exceeds the map boundary, Leaflet will reposition it, which may cause the top of popup to be outside the visible screen area.

**Comment by MichalD96** [comment]
Great job.
I found one little bug. FME image should be white, but is purple.
image

This font is really hard to read (everywhere). Can you make it a little bit bigger, increase kerning (letter-spacing) or change it to not that super narrow font?
image

X to close box with map coordinates is dark:
image

**Comment by gebederry** [comment]
@MichalD96 
I previously set the 'letter-spacing' of popup-links buttons to `0.05em` individually, now changed it to `0.075em` to make it consistent with the 'letter-spacing' of other buttons' fonts. BTW the text in your screenshot looks weird, with inconsistent font height. I remember this only happens when the font size is set to `14px` or below.
I’ve now increased the font size by 1 step for all buttons using this font.

As for this font, well, it’s the one used by the Wheeler, Rawson online store for displaying categories and buttons. However, the overall font size on their page is quite large, making it look comfortable. This font is about two sizes smaller than usual and has narrower 'letter-spacing'. My intention was to add a font that would allow users to easily distinguish buttons from regular text visually, I thought [RDRCatalogueBold](https://s.rsg.sc/sc/fonts/rdr2catalogue/catalog-bold/RDRCatalogueBold-Bold.woff2) was just right.

Maybe we’ll gradually get used to it and could always fine-tune it later for better visual performance.

Impulsively changed the 'fme-image' to purple XD. Reverted.

**Comment by MichalD96** [comment]
Ok, it's better now, but that font still needs some adjustments.

**Review by MichalD96 — APPROVED** [review]

**Pull request merged**
