### PR TITLE
Content generation simplification

### PR DESCRIPTION
**Pull request by siemer**

### CODE REVIEW

**Comment by MichalD96** [comment]
- inventory doesn't work, not load the items
- custom user pins popups layout is wrong

**Comment by siemer** [comment]
Those msgs are easy to miss here...

Do you mind commenting on a code line in one of my commits? I would like to see what kind of notifications I get...

**Comment by MichalD96** [comment]
yes, i know it is easy to miss, that's why i wrote to you on discord
Do you want that i write inline comment now? sure, i can write

**Comment by siemer** [comment]
If it is on a line in a commit I think it is best to commit inline here and maybe ping in discord.

**Pull request merged**
