### PR TITLE
Update fr-fr.json

### PR DESCRIPTION
**Pull request by LukyVj**
Just a few correction:
 
- `Réinitialiser` is better in this context than `Rétablir`
- `Presse-Papier` is singular. So no `s` at the end.

### CODE REVIEW

**Comment by Nopitch** [comment]
> Réinitialiser 
will mess the layout and it is not a realy french word.

**Comment by LukyVj** [comment]
I understand why you feel that way when someone is updating content you wrote. 

However, please explain me how "Réinitialiser" isn't french ( https://www.larousse.fr/dictionnaires/francais/r%C3%A9initialiser/186706 ) 

Also, as a web developer working in this field since a decade, I know that if a word will "mess with the layout" then it means that the layout might not be ideal. 

No hard feeling tho, I let @jeanropke decide what's best for his tool. 

Cheers :)

**Comment by Nopitch** [comment]
Hi,

Don’t get me wrong I’m happy to have some help with the French translation. 

But I insist google translate is not a reliable source, and read the definition in your link. Réinitialiser means rétablir. 
The best source for French is https://www.cnrtl.fr/.

**Comment by LukyVj** [comment]
> You can also say "un presse-papiers " but why not

For this, I guess I'll trust you. It just sounded weird as I barely encounter "press-papiers" on the web :)

**Comment by LukyVj** [comment]
So I'll be honest with you, if I see "retablir" on a web application, it will probably takes me more time to realize that the developer implies "reset", hence why I suggested to replace it with something which, in this context, appear to be more appropriate :)

**Comment by Nopitch** [comment]
I know but look :
paramètres

paramètres2

**Comment by LukyVj** [comment]
I give you that, indeed. The second screenshot doesn’t shock me, but I see what you mean. 

That being said, I wonder how the German translation are going 😂

Just an idea but maybe having a clear fix right after the label would be a better solution, but I’ll let you guys handle that :)

**Comment by Nopitch** [comment]
I just give my opinion i'm like you, i'm here to help i handle nothing ;)

**Comment by Megalex42** [comment]
I'm gonna second @LukyVj on this one.

According to the grand dictionnaire terminologique, "Reset" in the computer sense translates to réinitialiser

http://www.granddictionnaire.com/ficheOqlf.aspx?Id_Fiche=8392800

**Comment by Nopitch** [comment]
I changed the "Rétablir" with "Réinitialiser" as requested in this meger request in the #368 commit that has been merged.

**Pull request closed without merging**
