### PR TITLE
Item class and weekly

### PR DESCRIPTION
**Pull request by siemer**

### CODE REVIEW

**Comment by MichalD96** [comment]
Items value counter doesn't work if you have disabled "Toggle menu items updates inventory"

**Comment by MichalD96** [comment]
`TypeError: Collection.collections[category] is undefined`  if you disable random spot

**Comment by siemer** [comment]
Good work!—I’m out eating right now, but I also encountered dependency conflicts with further work I just did.

You can check my fork, branch “dependency”. That resolved my problems. But I think that there is a circular dependency between the init code of cycles.js and map.js.

I’ll investigate further later.

**Comment by siemer** [comment]
I rebased and added two commits.

`weeklySetData.sets` does not exist any more.

I tried to trigger more load issues, but can’t see any at the moment. How about you?

**Comment by MichalD96** [comment]
I dont have any problems with loading markers now

**Pull request merged**
