### PR TITLE
split language.js

### PR DESCRIPTION
**Pull request by siemer**
I chose two new file names to avoid oversight, but I don’t mind using other names. Just drop a line.

language.js → language-code.js + /langs/language-data-min.js

Who handles all language minimization tooling?

### CODE REVIEW

**Comment by siemer** [comment]
Okay, so that debug functionality is the current tool in use! I remember some “private” tool mentioned on discord some weeks back.

**Comment by Senexis** [comment]
It's in use by me because I didn't want to wait for Jean to send me the program he wrote. Whether he's still using it is unknown to me. @jeanropke

**Comment by jeanropke** [comment]
Not the best code, but it's works ¯\_(ツ)_/¯
https://pastebin.com/TdE7derr

**Comment by Senexis** [comment]
Not why I tagged ya. Haha. Do you still use it instead of generate langs?

**Pull request closed without merging**
